---
- name : Download epel-release-latest-8.noarch.rpm
  get_url:
    url: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    dest: /tmp/epel-release-latest-8.noarch.rpm

- name: Install EPEL Repo 8
  yum:
    name:
      - /tmp/epel-release-latest-8.noarch.rpm
    state: present

- name: Install Remi Repo and Enable remi repo
  yum:
    name:
      - https://rpms.remirepo.net/enterprise/remi-release-8.rpm

- name: Reset php module
  shell: dnf module reset php -y

- name: Enable module php:remi-7.3
  shell: yum module enable php:remi-7.3 -y

- name: Install php-fpm and deps
  yum:  
    name:
      - php
      - php-cli
      - php-common
      - php-fpm
      - php-mysqlnd
      - php-dom
      - php-simplexml
      - php-ssh2
      - php-xml
      - php-xmlreader
      - php-curl
      - php-date
      - php-exif
      - php-filter
      - php-ftp
      - php-gd
      - php-hash
      - php-iconv
      - php-json
      - php-libxml
      - php-pecl-imagick
      - php-mbstring
      - php-mysqlnd
      - php-openssl
      - php-pcre
      - php-posix
      - php-sockets
      - php-spl
      - php-tokenizer
      - php-zlib
    state: present

- name: Create a directory /var/run/php if it does not exist
  file:
    path: /var/run/php
    state: directory
    mode: '0755'

- name: Create a directory /srv/wordpress if it does not exist
  file:
    path: /srv/wordpress
    state: directory
    mode: '0755'

- name: Add wordpress user
  user:
    name: wordpress

- name: Disable default pool
  command: mv /etc/php-fpm.d/www.conf /etc/php-fpm.d/www.disabled creates=/etc/php-fpm.d/www.disabled
  notify: restart php-fpm.service

- name: Copy php-fpm configuration
  template: src=wordpress.conf dest=/etc/php-fpm.d/
  notify: restart php-fpm.service
