---
- name : Download epel-release-latest-7.noarch.rpm
  get_url: 
    url: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    dest: /tmp/epel-release-latest-7.noarch.rpm

- name: Install EPEL Repo 7
  yum:
    name:
      - /tmp/epel-release-latest-7.noarch.rpm
    state: present

- name: Install Remi Repo and Enable remi repo
  yum:
    name:
      - http://rpms.remirepo.net/enterprise/remi-release-7.rpm

- name: Install yum-utils
  yum:
    name:
      - yum-utils
    state: present

- name: enable remi-php72
  shell: yum-config-manager --enable remi-php72

- name: Upgrade all Packages
  yum:
    name: "*"
    state: latest

- name: Install php-fpm and deps
  yum:  
    name:
      - php72
      - php72-php-fpm
      - php72-php-enchant
      - php72-php-mbstring
      - php72-php-mysql
      - php72-php-process
      - php72-php-xml
      - php72-php-json
      - php72-php-mysqlnd
      - php72-php-xmlrpc
      - php72-php-opcache
    state: present

- name: Create a directory /var/run/php-fpm if it does not exist
  file:
    path: /var/run/php-fpm
    state: directory
    mode: '0755'

- name: Create a directory /srv/wordpress if it does not exist
  file:
    path: /srv/wordpress
    state: directory
    mode: '0755'

- name: Add wordpress user
  user:
    name: wordpress

- name: Disable default pool
  command: mv /etc/opt/remi/php72/php-fpm.d/www.conf /etc/opt/remi/php72/php-fpm.d/www.disabled creates=/etc/opt/remi/php72/php-fpm.d/www.disabled
  notify: restart php72-php-fpm.service

- name: Copy php-fpm configuration
  template: src=wordpress.conf dest=/etc/opt/remi/php72/php-fpm.d/
  notify: restart php72-php-fpm.service
