---
- name: Install WordPress, Nginx, and PHP-FPM
  hosts: webserver
  remote_user: ec2-user
  # remote_user: user
  become: yes
  become_method: sudo
  roles:
    - common
    - nginx
    - php-fpm
    - wordpress

- name: Install MySQL
  hosts: database
  remote_user: ec2-user
  # remote_user: user
  become: yes
  become_method: sudo
  roles:
    - common
    - mysql